name: Create EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  create-ec2-instance:
    runs-on: ubuntu-latest
    steps:
      # Checkout code from git repo branch configure above
      - name: Checkout
        uses: actions/checkout@v2

      # Sets up AWS profile.  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: get EC2 Instance ID
        if: ${{ vars.ACTION == 'stop' }}
        run: |
          instance_id=$(aws ec2 describe-instances --filters Name=tag:Name,Values=test --query 'Reservations[*].Instances[*].InstanceId' --output text)
      - name: Stop EC2 instance
        run: |
          aws ec2 stop-instances --instance-ids $instance_id