name: Create EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  create-ec2-instance:
    runs-on: ubuntu-latest
    steps:
      # Checkout code from git repo branch configure above
      - name: Checkout
        uses: actions/checkout@v2

      # Sets up AWS profile.  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create EC2 Instance
        run: |
          aws ec2 run-instances \
            --image-id ami-04cb4ca688797756f \
            --instance-type t2.micro \
            --security-group-ids sg-0e2c4f83cb6112721 \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=development}]'