name: Create EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  create-ec2-instance:
    runs-on: ubuntu-latest
    steps:
      # Checkout code from git repo branch configure above
      - name: Checkout
        uses: actions/checkout@v2

      # Sets up AWS profile.  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create EC2 Instance
        if: ${{ vars.ACTION == 'create' }}
        run: |
          aws ec2 run-instances \
            --image-id ami-04cb4ca688797756f \
            --instance-type t2.micro \
            --subnet-id ${{ vars.SUBNET_ID }} \
            --security-group-ids ${{ vars.SECURITY_GROUP_ID }} \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=development1}]'	
      - name: get EC2 Instance ID
        if: ${{ vars.ACTION == 'stop' }}
        id: get-instance-id
        run: |
          instance_id=$(aws ec2 describe-instances --filters Name=tag:Name,Values=development1 --query 'Reservations[*].Instances[*].InstanceId' --output text)
          echo "::set-output name=instance_id::$instance_id"
      - name: Stop EC2 instance
        if: ${{ vars.ACTION == 'stop' }}
        run: |
          instance_id="${{ steps.get-instance-id.outputs.instance_id }}"
          aws ec2 stop-instances --instance-ids $instance_id
      - name: Terminate EC2 instance
        if: ${{ vars.ACTION == 'terminate' }}
        run: |
          instance_id="${{ steps.get-instance-id.outputs.instance_id }}"
          aws ec2 terminate-instances --instance-ids $instance_id
          