name: Create EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  create-ec2-instance:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: actions/checkout@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create EC2 Instance
        run: |
          aws ec2 create-instances \
            --image-id ami-123456789012 \
            --instance-type t2.micro \
            --vpc-id vpc-05d02b24334d76cbe \
            --security-group-ids sg-0e2c4f83cb6112721 